# Generated by Django 5.1.2 on 2024-10-27 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buz_token", "0002_create_task_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buztoken",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Buz Tokens"},
        ),
        migrations.AddIndex(
            model_name="buztoken",
            index=models.Index(
                fields=["user", "channel"], name="buz_token_b_user_id_16bcb9_idx"
            ),
        ),
    ]
