# Generated by Django 5.1.2 on 2024-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buz_token", "0002_create_task_data"),
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertask",
            options={},
        ),
        migrations.AddConstraint(
            model_name="usertask",
            constraint=models.UniqueConstraint(
                fields=("user", "task"), name="unique_user_task"
            ),
        ),
    ]
