# Generated by Django 5.1.2 on 2024-10-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buz_token", "0003_alter_usertask_options_usertask_unique_user_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="buztoken",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
