# Generated by Django 5.1.2 on 2024-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buz_token", "0004_buztoken_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
