# Generated by Django 5.1.2 on 2024-10-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
