# Generated by Django 5.1.2 on 2024-10-14 13:10

import config.model_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=config.model_utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "referred",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.SET,
                        related_name="referred",
                        to="users.user",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET,
                        related_name="referals",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("referred_id", models.F("referrer_id")), _negated=True
                        ),
                        name="check_referred_not_referer",
                    )
                ],
            },
        ),
    ]
