# Generated by Django 5.1.2 on 2024-10-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referred",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.SET,
                related_name="referrer",
                to="users.user",
            ),
        ),
    ]
