# Generated by Django 5.1.2 on 2024-10-17 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0002_create_question_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userquestion",
            options={},
        ),
        migrations.AddConstraint(
            model_name="userquestion",
            constraint=models.UniqueConstraint(
                fields=("user", "question"), name="unique_user_question"
            ),
        ),
    ]
